import json
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from backend.services.project_service import get_project


CREATORFORGE_VERSION = "0.6.6"


def create_project_export(project_id: str) -> Path:
    project = get_project(project_id)
    export_directory = Path(tempfile.mkdtemp(prefix="creatorforge-export-"))
    archive_path = export_directory / f"creatorforge-project-{project_id}.zip"

    with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("README.txt", _build_readme(project))
        archive.writestr(
            "project.json",
            json.dumps(project, indent=2, ensure_ascii=False),
        )
        archive.writestr("research.md", _text(project.get("research")))
        archive.writestr(
            "research_summary.md",
            _text(project.get("research_summary")),
        )
        archive.writestr("outline.md", _text(project.get("outline")))
        archive.writestr("titles.txt", "\n".join(_text_list(project.get("titles"))))
        archive.writestr("script.md", _text(project.get("script")))
        archive.writestr("description.md", _text(project.get("description")))
        archive.writestr("tags.txt", ", ".join(_text_list(project.get("tags"))))
        archive.writestr(
            "thumbnail_prompt.txt",
            _text(project.get("thumbnail_prompt")),
        )

    return archive_path


def _build_readme(project: dict[str, object]) -> str:
    export_date = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

    return "\n".join((
        "CreatorForge Project Export",
        "",
        f"Project name: {_text(project.get('topic'))}",
        f"Creation date: {_text(project.get('created'))}",
        f"Generator version: {_text(project.get('generator_version'))}",
        f"Export date: {export_date}",
        f"CreatorForge version: {CREATORFORGE_VERSION}",
        "",
        "This package was generated by CreatorForge.",
    ))


def _text(value: object) -> str:
    return value if isinstance(value, str) else ""


def _text_list(value: object) -> list[str]:
    if not isinstance(value, list):
        return []

    return [item for item in value if isinstance(item, str)]
